BATCH_SIZE = 16
HIDDEN_DIM = 128
NUM_LAYERS = 2
NUM_HEADS = 4
LEARNING_RATE = 3.742221410860518e-04
NUM_PREDS = 3
EARLY_STOP_PATIENCE = 20
WEIGHT_DECAY = 0.0001
POINTNET_OUTPUT_DIM = 64
POINTNETPP_OUTPUT_DIM = 128
MAX_EPOCHS = 20
SCHEDULER_STEP_SIZE = 8
SCHEDULER_GAMMA = 0.3
DIRECTION_LOSS_WEIGHT = 5.0
CONF_LOSS_WEIGHT = 0.1

RANDOM_STATE = 42
NUM_WORKERS = 2
NUM_FOLDS = 5
NUM_TRIALS = 200

LOG_DIR = "logs"
CKPT_DIR = "checkpoints"
DATASET_PATH = "dataset.npz" # "pointNetpp_embeddings.parquet"

NO_ATTN = False  # ablation: no attention, just feedforward